apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kf-autobot
resources:
- deployment.yaml
- service-account.yaml
images:
- digest: sha256:5f169ff3ad1e66d96643a68f330e78bcc78a5c4752b5f85de343220a60425dc2
  name: calendar
  newName: gcr.io/kf-infra-gitops/calendar-sync:9c5e87b-dirty
