apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kf-autobot
resources:
- deployment.yaml
- service-account.yaml
images:
- digest: sha256:49b7b067a354d6cdb898707eeb2a258405ce0e64e17b8b76f440a6d0b80defc2
  name: calendar
  newName: gcr.io/kf-infra-gitops/calendar-sync:2b76aca-dirty
