---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: devstats-nfs
  namespace: devstats
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 1000Gi
  nfs:
    # This should be the name of the fileshare in cloud filestore
    path: /kubeflow
    server: 10.23.251.218
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: devstats-nfs
  namespace: devstats
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-storage
  volumeName: devstats-nfs