---
columns:
  - table_regexp: '^scompany_activity$'
    tag: tcompanies
    column: companies_name
  - table_regexp: '^scountries'
    tag: tcountries
    column: country_name
  - table_regexp: '^stz$'
    tag: ttz_offsets
    column: tz_offset
