---
columns:
  - table_regexp: '^s(act|commits|grp_pr_merg)$'
    tag: trepo_groups
    column: repo_group_name
  - table_regexp: '^scompany_activity$'
    tag: tcompanies
    column: companies_name
  - table_regexp: '^suser_activity$'
    tag: tusers
    column: users_name
  - table_regexp: '^suser_reviews$'
    tag: treviewers
    column: reviewers_name
  - table_regexp: '^si(open|clos)ed$'
    tag: tall_repo_groups
    column: all_repo_group_value
  - table_regexp: '^spr_appr'
    tag: tall_repo_groups
    column: all_repo_group_value
  - table_regexp: '^sevent_types$'
    tag: tevent_types
    column: event_type_name
  - table_regexp: '^scountries'
    tag: tcountries
    column: country_name
  - table_regexp: '^stz$'
    tag: ttz_offsets
    column: tz_offset
