apiVersion: 0.3.0
environments:
  devstats2:
    destination:
      namespace: devstats
      server: https://35.193.107.91
    k8sVersion: v1.11.6
    path: devstats2
kind: ksonnet.io/app
libraries:
  kubeflow/core:
    name: core
    registry: kubeflow
    version: e2c2c7c49e578472ba57f91f3b2a5f4d1a2d0289
name: ks-app
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/master/kubeflow
version: 0.0.1
