# config file version
apiVersion: 1

# list of datasources to insert/update depending
# what's available in the database
datasources:
  # <string, required> name of the datasource. Required
  # name should match the value defined in the dasbhoard 
- name: psql
  # <string, required> datasource type. Required
  type: postgres
  # <string, required> access mode. proxy or direct (Server or Browser in the UI). Required
  access: direct
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: devstatsdb-0.devstatsdb.devstats.svc.cluster.local
  # <string> database password, if used
  # <string> database user, if used
  user: gha_admin
  # <string> database name, if used
  database: kubeflow
  secureJsonData:
    password: "password"
  jsonData:
    sslmode: "disable" # disable/require/verify-ca/verify-full
    maxOpenConns: 0         # Grafana v5.4+
    maxIdleConns: 2         # Grafana v5.4+
    connMaxLifetime: 14400  # Grafana v5.4+
    postgresVersion: 903 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
    timescaledb: false

# 